### ISSUE TITLE
Buidling a `.deb` fails with "dpkg-checkbuilddeps: error: Unmet build dependencies: python3-flask-httpauth"

### ISSUE THREAD

**Issue by meitar** [micahflee/onionshare#1005]
On a newly installed Raspbian OS ("Debian-derived") system, I'm following the `BUILD.md` file's instructions for creating a `.deb` package file, but cannot build due to the error above. My command history is as follows:

```sh
cd $HOME
git clone https://github.com/micahflee/onionshare.git
cd onionshare
sudo apt install -y python3-flask python3-stem python3-pyqt5 python3-crypto python3-socks python-nautilus tor obfs4proxy python3-pytest build-essential fakeroot python3-all python3-stdeb dh-python
```

At this point, my system is still missing Flask-HTTPAuth, and there is no `python3-flask-httpauth` package to be found. Am I to understand that installing `python3-flask` installs the Flask-HTTPAuth package on other distros? Observe:

```sh
pi@raspberry:~/onionshare $ ./dev_scripts/onionshare
Traceback (most recent call last):
  File "./dev_scripts/onionshare", line 27, in <module>
    import onionshare
  File "/home/pi/onionshare/onionshare/__init__.py", line 26, in <module>
    from .web import Web
  File "/home/pi/onionshare/onionshare/web/__init__.py", line 21, in <module>
    from .web import Web
  File "/home/pi/onionshare/onionshare/web/web.py", line 14, in <module>
    from flask_httpauth import HTTPBasicAuth
ImportError: No module named 'flask_httpauth'
```

There *is* a package named `python-flask-httpauth`, but this is a Python 2.7 codebase. Installing it doesn't work:

```sh
pi@raspberry:~/onionshare $ apt search flask-httpauth
Sorting... Done
Full Text Search... Done
python-flask-httpauth/stable,stable 3.2.1-1 all
  Basic and Digest HTTP authentication for Flask routes

pi@raspberry:~/onionshare $ sudo apt install python-flask-httpauth
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  python-flask-httpauth
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 37.0 kB of archives.
After this operation, 182 kB of additional disk space will be used.
Get:1 http://ftp.debian.org/debian stretch/main i386 python-flask-httpauth all 3.2.1-1 [37.0 kB]
Fetched 37.0 kB in 0s (83.6 kB/s)              
Selecting previously unselected package python-flask-httpauth.
(Reading database ... 131672 files and directories currently installed.)
Preparing to unpack .../python-flask-httpauth_3.2.1-1_all.deb ...
Unpacking python-flask-httpauth (3.2.1-1) ...
Setting up python-flask-httpauth (3.2.1-1) ...
Processing triggers for man-db (2.7.6.1-2) ...
pi@raspberry:~/onionshare $ ./dev_scripts/onionshare
Traceback (most recent call last):
  File "./dev_scripts/onionshare", line 27, in <module>
    import onionshare
  File "/home/pi/onionshare/onionshare/__init__.py", line 26, in <module>
    from .web import Web
  File "/home/pi/onionshare/onionshare/web/__init__.py", line 21, in <module>
    from .web import Web
  File "/home/pi/onionshare/onionshare/web/web.py", line 14, in <module>
    from flask_httpauth import HTTPBasicAuth
ImportError: No module named 'flask_httpauth'
```

So, I removed it and then used `pip3` to install the `Flask-HTTPAuth` package from PyPi, which *did* resolve the import error:

```sh
pi@raspberry:~/onionshare $ sudo pip3 install Flask-HTTPAuth
Collecting Flask-HTTPAuth
  Downloading https://files.pythonhosted.org/packages/b9/fd/89fc9aa163b5a7aa809fac0835502c2b66f48a5114a73df7e2a104cc645f/Flask_HTTPAuth-3.3.0-py2.py3-none-any.whl
Requirement already satisfied: Flask in /usr/lib/python3/dist-packages (from Flask-HTTPAuth)
Installing collected packages: Flask-HTTPAuth
Successfully installed Flask-HTTPAuth-3.3.0
pi@raspberry:~/onionshare $ ./dev_scripts/onionshare
OnionShare 2.1 | https://onionshare.org/
[…TRIMMED FOR LENGTH…]
```

At this point, I can run OnionShare without problems using the dev scripts, however I still cannot build a `.deb` because (apparently?) [the `stdeb.cfg` file is instructing the `python3-stdeb` code to require the `python3-flask-httpauth` package](https://github.com/micahflee/onionshare/blob/develop/stdeb.cfg#L3-L4). So, an attempt to build a `.deb` fails like this:

```sh
pi@raspberry:~/onionshare $ ./install/build_deb.sh
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
running bdist_deb
running sdist_dsc
running sdist
running check
warning: sdist: standard file not found: should have one of README, README.txt

reading manifest template 'MANIFEST.in'
warning: no files found matching 'share/static/*'
writing manifest file 'MANIFEST'
creating onionshare-2.1
creating onionshare-2.1/install
creating onionshare-2.1/install/scripts
creating onionshare-2.1/onionshare
creating onionshare-2.1/onionshare/web
creating onionshare-2.1/onionshare_gui
creating onionshare-2.1/onionshare_gui/mode
creating onionshare-2.1/onionshare_gui/mode/receive_mode
creating onionshare-2.1/onionshare_gui/mode/share_mode
creating onionshare-2.1/onionshare_gui/mode/website_mode
creating onionshare-2.1/share
creating onionshare-2.1/share/images
creating onionshare-2.1/share/locale
creating onionshare-2.1/share/static
creating onionshare-2.1/share/static/css
creating onionshare-2.1/share/static/img
creating onionshare-2.1/share/static/js
creating onionshare-2.1/share/templates
creating onionshare-2.1/tests
making hard links in onionshare-2.1...
hard linking BUILD.md -> onionshare-2.1
hard linking LICENSE -> onionshare-2.1
hard linking README.md -> onionshare-2.1
hard linking setup.cfg -> onionshare-2.1
hard linking setup.py -> onionshare-2.1
[…TRIMMED "hard linking" OUTPUT FOR LENGTH…]
creating dist
Creating tar archive
removing 'onionshare-2.1' (and everything under it)
CALLING dpkg-source -b onionshare-2.1 onionshare_2.1.orig.tar.gz (in dir deb_dist)
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building onionshare using existing ./onionshare_2.1.orig.tar.gz
dpkg-source: info: building onionshare in onionshare_2.1-1.debian.tar.xz
dpkg-source: info: building onionshare in onionshare_2.1-1.dsc
dpkg-buildpackage: info: source package onionshare
dpkg-buildpackage: info: source version 2.1-1
dpkg-buildpackage: info: source distribution cosmic
dpkg-buildpackage: info: source changed by Micah Lee <micah@micahflee.com>
 dpkg-source --before-build onionshare-2.1
dpkg-checkbuilddeps: error: Unmet build dependencies: python3-flask-httpauth
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
Traceback (most recent call last):
  File "setup.py", line 96, in <module>
    data_files=data_files
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/stdeb/command/bdist_deb.py", line 22, in run
    self.run_command('sdist_dsc')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/stdeb/command/sdist_dsc.py", line 140, in run
    remove_expanded_source_dir=self.remove_expanded_source_dir,
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 1397, in build_dsc
    dpkg_genchanges(cwd=fullpath_repackaged_dirname)
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 538, in dpkg_genchanges
    process_command(args,cwd=cwd)
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 183, in process_command
    check_call(args, cwd=cwd)
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 46, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 3
OnionShare failed to build!
```

If I remove the `python3-flask-httpauth` names from the `stdeb.cfg` file's `Depends3` and `Build-Depends3` lines, the `./install/build_deb.sh` script will succeed *and* I can apparently run OnionShare without issues. Importantly, HTTP authentication still works because Flask is still able to import the `Flask-HTTPAuth` package installed manually via `pip3`, earlier.

I don't know enough about packaging to know what the correct solution to this problem is, but figured I would post an issue here to let OnionShare developers know I'm running into the issue and to let other users who may run into the same dependency error learn about the workaround I described above.

Thanks again for a wonderful tool.

**Comment by meitar** [comment]
I was able to automate the workaround described above in [AnarchoTechNYC/ansible-role-onionshare commit 9fb4cab5](https://github.com/AnarchoTechNYC/ansible-role-onionshare/commit/9fb4cab5803b7207a469cc891a958c358bead733) for those who want more detail.

**Comment by mig5** [comment]
I'm going to close this as indeed we will be depending on `python3-flask-httpauth` for building debs in future (meaning only versions of Debian/Ubuntu that have that package will be able to build an OnionShare 2 .deb).

The alternative is indeed to pip install the flask-httpauth package and then rely on running OnionShare via the scripts located in the  `dev_scripts` folder of this git repo.
