### ISSUE TITLE
Onionshare doest start anymore in linux mint

### ISSUE THREAD

**Issue by Yagami-ya** [micahflee/onionshare#1008]
I am curious to know if it reccurent or not but since fews week after updated linux mint Onionshare doest works anymore. I deleted and re installed the latest update.

I launch it I can see the icon loading and then nothing appears...

Did you ever encouter this problem or do I need new package to make it run porperly?

**Comment by mig5** [comment]
Hi @Yagami-ya 

It's hard to say what would cause this without more debug info.

Please open a Terminal and try to run it from the command line:

```
onionshare-gui --debug
```

If you get an error about `--debug` not being a valid parameter, try:

```
onionshare-gui --verbose
```

**Comment by Yagami-ya** [comment]
Hello thank you for your help,

I tried the first line command and this is the result:

`~$ onionshare-gui --debug
Traceback (most recent call last):
  File "/usr/bin/onionshare-gui", line 21, in <module>
    import onionshare_gui
  File "/usr/lib/python3/dist-packages/onionshare_gui/__init__.py", line 29, in <module>
    from onionshare.common import Common
  File "/usr/lib/python3/dist-packages/onionshare/__init__.py", line 27, in <module>
    from .onion import *
  File "/usr/lib/python3/dist-packages/onionshare/onion.py", line 21, in <module>
    from stem.control import Controller
  File "/usr/lib/python3/dist-packages/stem/control.py", line 265, in <module>
    import stem.descriptor.microdescriptor
  File "/usr/lib/python3/dist-packages/stem/descriptor/__init__.py", line 55, in <module>
    import stem.util.system
  File "/usr/lib/python3/dist-packages/stem/util/system.py", line 70, in <module>
    import distutils.spawn
ModuleNotFoundError: No module named 'distutils.spawn'`

**Comment by dumdumdugan** [comment]
This is the same output I get on Ubuntu 18.04 LTS install. thank you for the solution

**Comment by mig5** [comment]
We have this also reported at #1010 , you might find that installing `python3-distutils` fixes it (until we fix it properly as a dependency).
