### ISSUE TITLE
Dependency issue in Ubuntu 18.04

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#1010]
I got a report that this happens when trying to run OnionShare in Ubuntu 18.04 LTS:

```onionshare-gui 
Traceback (most recent call last):
  File "/usr/bin/onionshare-gui", line 21, in <module>
    import onionshare_gui
  File "/usr/lib/python3/dist-packages/onionshare_gui/init.py", line 29, in <module>
    from onionshare.common import Common
  File "/usr/lib/python3/dist-packages/onionshare/init.py", line 27, in <module>
    from .onion import *
  File "/usr/lib/python3/dist-packages/onionshare/onion.py", line 21, in <module>
    from stem.control import Controller
  File "/usr/lib/python3/dist-packages/stem/control.py", line 265, in <module>
    import stem.descriptor.microdescriptor
  File "/usr/lib/python3/dist-packages/stem/descriptor/init.py", line 55, in <module>
    import stem.util.system
  File "/usr/lib/python3/dist-packages/stem/util/system.py", line 70, in <module>
    import distutils.spawn
ModuleNotFoundError: No module named 'distutils.spawn'
```

**Comment by mig5** [comment]
This came up in December and was apparently fixed in #715 and #854. So what's happened here? :s Did it somehow escape the PPA release?

**Comment by garethjordan** [comment]
Ah, pleased to find this. I get similar on Linux Mint 19.1 Cinnamon:

Traceback (most recent call last):
  File "/usr/bin/onionshare", line 21, in <module>
    import onionshare
  File "/usr/lib/python3/dist-packages/onionshare/__init__.py", line 27, in <module>
    from .onion import *
  File "/usr/lib/python3/dist-packages/onionshare/onion.py", line 21, in <module>
    from stem.control import Controller
  File "/usr/lib/python3/dist-packages/stem/control.py", line 265, in <module>
    import stem.descriptor.microdescriptor
  File "/usr/lib/python3/dist-packages/stem/descriptor/__init__.py", line 55, in <module>
    import stem.util.system
  File "/usr/lib/python3/dist-packages/stem/util/system.py", line 70, in <module>
    import distutils.spawn
ModuleNotFoundError: No module named 'distutils.spawn'

**Comment by garethjordan** [comment]
Yes.
Installed python3-distutils and python3-distutils-extra and all works now.
