### ISSUE TITLE
OnionShare 2.2 crashing in macOS

### ISSUE THREAD

**Issue by SpectyteCovelight** [micahflee/onionshare#1050]
I've installed the app on MacOS High Sierra latest version and can't load the app I dont know why, I hope the developer fix the issue

**Comment by micahflee** [comment]
Thanks for reporting! This actually should work in macOS High Sierra, however there's a critical bug related to the Mac build script. When running OnionShare from the command line it fails with this error:

```
$ /Applications/OnionShare.app/Contents/MacOS/onionshare-gui --help
Traceback (most recent call last):
  File "onionshare-pyinstaller", line 34, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "onionshare_gui/__init__.py", line 29, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "onionshare/__init__.py", line 26, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "onionshare/web/__init__.py", line 21, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "onionshare/web/web.py", line 12, in <module>
ModuleNotFoundError: No module named 'flask'
[15204] Failed to execute script onionshare-pyinstaller
```

**Comment by micahflee** [comment]
Sorry about that. I just re-built the binary, but this time correctly. Try downloading it again, it should work this time: https://onionshare.org/dist/2.2/
