### ISSUE TITLE
Stucking at "publication" using Whonix-OnionShare steps

### ISSUE THREAD

**Issue by TNTBOMBOM** [micahflee/onionshare#1067]
Following steps mentioned here:

https://www.whonix.org/wiki/OnionShare

(clicking on test tor gives true)

testing on standaloneVMs of whonix in Qubes its stucking at: 

```
user@host:~$ onionshare-gui
Onionshare 1.3.2 | https://onionshare.org/
Connecting to the Tor network: 100% - Done
Configuring onion service on port 17644.
Starting ephemeral Tor onion service and awaiting publication
Settings saved to /home/user/.config/onionshare/onionshare.json
Configuring onion service on port 17627.
Starting ephemeral Tor onion service and awaiting publication
```

Also it closed itself (one time happened): 

```
user@host:~$ onionshare-gui
Onionshare 1.3.2 | https://onionshare.org/
Connecting to the Tor network: 100% - Done
Settings saved to /home/user/.config/onionshare/onionshare.json
Configuring onion service on port 17607.
Starting ephemeral Tor onion service and awaiting publication
Configuring onion service on port 17621.
Starting ephemeral Tor onion service and awaiting publication
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/onionshare_gui/onionshare_gui.py", line 814, in run
    self.function(**self.kwargs)
  File "/usr/lib/python3/dist-packages/onionshare_gui/onionshare_gui.py", line 387, in start_onion_service
    self.app.start_onion_service()
  File "/usr/lib/python3/dist-packages/onionshare/onionshare.py", line 79, in start_onion_service
    self.onion_host = self.onion.start_onion_service(self.port)
  File "/usr/lib/python3/dist-packages/onionshare/onion.py", line 461, in start_onion_service
    res = self.c.create_ephemeral_hidden_service({ 80: port }, await_publication=True, key_type = key_type, key_content=key_content)
  File "/usr/lib/python3/dist-packages/stem/control.py", line 3015, in create_ephemeral_hidden_service
    response = self.msg(request)
  File "/usr/lib/python3/dist-packages/stem/control.py", line 658, in msg
    raise response
  File "/usr/lib/python3/dist-packages/stem/control.py", line 937, in _reader_loop
    control_message = self._socket.recv()
  File "/usr/lib/python3/dist-packages/stem/socket.py", line 464, in recv
    return self._recv(lambda s, sf: recv_message(sf))
  File "/usr/lib/python3/dist-packages/stem/socket.py", line 278, in _recv
    return handler(my_socket, my_socket_file)
  File "/usr/lib/python3/dist-packages/stem/socket.py", line 464, in <lambda>
    return self._recv(lambda s, sf: recv_message(sf))
  File "/usr/lib/python3/dist-packages/stem/socket.py", line 693, in recv_message
    raise stem.SocketClosed('Received empty socket content.')
stem.SocketClosed: Received empty socket content.
Aborted (core dumped)
```

**Comment by mig5** [comment]
Sounds like an issue communicating with Tor (not something OnionShare can fix). It will be hard to reproduce.

Can you run with `--debug` or `--verbose` flags to obtain more information? (You seem to be using an old version of OnionShare, 1.3.1, so might be `--debug` rather than `--verbose`). You could also try upgrading to v2.2 to see if that makes any difference (probably not)

**Comment by TNTBOMBOM** [comment]
> You seem to be using an old version of OnionShare, 1.3.1, so might be --debug

yes thats what it comes from debian stable repo. 

Btw i have solved the issue by restarting both GW,WS : 

```
user@host:~$ onionshare-gui --debug
Onionshare 1.3.2 | https://onionshare.org/
[Nov 04 2019 06:11:09 AM] Onion.__init__
[Nov 04 2019 06:11:09 AM] OnionShare.__init__
[Nov 04 2019 06:11:10 AM] OnionShareGui.__init__
[Nov 04 2019 06:11:10 AM] Settings.__init__
[Nov 04 2019 06:11:10 AM] Settings.load
[Nov 04 2019 06:11:10 AM] Settings.load: Trying to load /home/user/.config/onionshare/onionshare.json
[Nov 04 2019 06:11:10 AM] OnionShareGui.update_server_status_indicator
[Nov 04 2019 06:11:10 AM] TorConnectionDialog.__init__
[Nov 04 2019 06:11:10 AM] TorConnectionDialog.start
[Nov 04 2019 06:11:10 AM] TorConnectionThread.__init__
[Nov 04 2019 06:11:10 AM] TorConnectionThread.run
[Nov 04 2019 06:11:10 AM] Onion.connect
[Nov 04 2019 06:11:10 AM] TorConnectionDialog._connected_to_tor
[Nov 04 2019 06:11:20 AM] OnionShareGui.start_server
[Nov 04 2019 06:11:20 AM] OnionShare.set_stealth: stealth=False
[Nov 04 2019 06:11:20 AM] OnionshareGui.start_server: Starting an onion thread
[Nov 04 2019 06:11:20 AM] OnionThread.__init__
[Nov 04 2019 06:11:20 AM] OnionShareGui.update_server_status_indicator
[Nov 04 2019 06:11:20 AM] OnionThread.run
[Nov 04 2019 06:11:20 AM] OnionShare.start_onion_service
[Nov 04 2019 06:11:20 AM] Onion.start_onion_service
Configuring onion service on port 17619.
Starting ephemeral Tor onion service and awaiting publication
[Nov 04 2019 06:11:20 AM] Onion.Starting a hidden service with a new private key
[Nov 04 2019 06:11:53 AM] Settings.save
Settings saved to /home/user/.config/onionshare/onionshare.json
[Nov 04 2019 06:11:53 AM] OnionShareGui.start_server_step2
 * Serving Flask app "onionshare.web" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
[Nov 04 2019 06:11:53 AM] OnionShareGui.start_server_step3
[Nov 04 2019 06:11:53 AM] OnionShareGui.copy_url
[Nov 04 2019 06:11:53 AM] OnionShareGui.update_server_status_indicator
 * Running on http://0.0.0.0:17619/ (Press CTRL+C to quit)
[Nov 04 2019 06:12:31 AM] OnionShareGui.copy_url
10.137.0.7 - - [04/Nov/2019 06:12:43] "GET /reggae-duplex HTTP/1.1" 200 -
[Nov 04 2019 06:12:59 AM] OnionShareGui.stop_server
[Nov 04 2019 06:12:59 AM] OnionShare.cleanup
[Nov 04 2019 06:12:59 AM] Onion.cleanup
[Nov 04 2019 06:12:59 AM] Onion.cleanup: trying to remove onion f2uk2l2zpe2ysbgm
[Nov 04 2019 06:12:59 AM] OnionShareGui.update_server_status_indicator
[Nov 04 2019 06:12:59 AM] OnionShareGui.update_server_status_indicator
[Nov 04 2019 06:13:05 AM] OnionShareGui.closeEvent
[Nov 04 2019 06:13:05 AM] Onion.cleanup
[Nov 04 2019 06:13:05 AM] OnionShare.cleanup
user@host:~$ 
```

Thanks for the help though :)
