### ISSUE TITLE
OnionShare Crashing

### ISSUE THREAD

**Issue by lobome** [micahflee/onionshare#1071]
OnionShare 2.2 | https://onionshare.org/
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/onionshare_gui/onionshare_gui.py", line 543, in open_settings
d = SettingsDialog(
File "/usr/lib/python3.8/site-packages/onionshare_gui/settings_dialog.py", line 720, in __init__
self.reload_settings()
File "/usr/lib/python3.8/site-packages/onionshare_gui/settings_dialog.py", line 869, in reload_settings
if self.onion.supports_v3_onions:

AttributeError: 'Onion' object has no attribute 'supports_v3_onions'
Aborted (core dumped)

 when running it, it starts with a notification with the below and when I try to click settings button it crashes

>OnionShare could not connect to Tor in the background:
dictionary keys changed during iteration
Try changing how OnionShare connects to the Tor network in the settings.

I tried starting tor and then running onionshare but still not working

**Comment by Mati20187** [comment]
I have the exact same issue on Arch Linux, OnionShare 2.2-2

**Comment by mig5** [comment]
This should be fixed in `develop` branch now.
