### ISSUE TITLE
[Bug] Persistent mode does not work

### ISSUE THREAD

**Issue by Kcchouette** [micahflee/onionshare#1283]
## How to reproduce
 
- install onionshare-cli 2.3
 - launch with `onionshare-cli --public --website --persistent 'onionshare.session' --no-autostop-sharing 'folder/' --verbose`
   - please note that 'onionshare.session' does not exist, so onionshare will create and populate it
- go to the website, it works
- stop onionshare
- relaunch using the same command from the 2nd point
- now it shows you 500 error
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

## from the debug:
```
ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/usr/local/lib/python3.7/dist-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1744, in handle_http_exception
    return handler(e)
  File "/usr/local/lib/python3.7/dist-packages/onionshare_cli/web/web.py", line 229, in not_found
    history_id = mode.cur_history_id
AttributeError: 'NoneType' object has no attribute 'cur_history_id'
"GET / HTTP/1.1" 500 -
```

**Comment by Kcchouette** [comment]
Ok it seems it's because the mode is not set automatically in the file `onionshare.session`:

> "mode": null,

by setting it to "website" it sems loading but having another problem
