### ISSUE TITLE
Python exception when building on Mac OS X in a virtualenv

### ISSUE THREAD

**Issue by garrettr** [micahflee/onionshare#241]
On Mac OS 10.9, when following the build instructions for Mac OS X, I get the following error:

```
▶ ./install/build_osx.sh 
Deleting dist folder
Building OnionShare.app
running py2app
creating /Users/garrett/code/micahflee/onionshare/build
creating /Users/garrett/code/micahflee/onionshare/build/bdist.macosx-10.10-intel
creating /Users/garrett/code/micahflee/onionshare/build/bdist.macosx-10.10-intel/python2.7-semi_standalone
creating /Users/garrett/code/micahflee/onionshare/build/bdist.macosx-10.10-intel/python2.7-semi_standalone/app
creating /Users/garrett/code/micahflee/onionshare/build/bdist.macosx-10.10-intel/python2.7-semi_standalone/app/collect
creating /Users/garrett/code/micahflee/onionshare/build/bdist.macosx-10.10-intel/python2.7-semi_standalone/app/temp
creating /Users/garrett/code/micahflee/onionshare/dist
creating build/bdist.macosx-10.10-intel/python2.7-semi_standalone/app/lib-dynload
creating build/bdist.macosx-10.10-intel/python2.7-semi_standalone/app/Frameworks
Traceback (most recent call last):
  File "setup.py", line 129, in <module>
    setup_requires=['py2app', 'flask', 'stem'],
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/garrett/code/micahflee/onionshare/env/lib/python2.7/site-packages/py2app/build_app.py", line 659, in run
    self._run()
  File "/Users/garrett/code/micahflee/onionshare/env/lib/python2.7/site-packages/py2app/build_app.py", line 865, in _run
    self.run_normal()
  File "/Users/garrett/code/micahflee/onionshare/env/lib/python2.7/site-packages/py2app/build_app.py", line 943, in run_normal
    self.process_recipes(mf, filters, flatpackages, loader_files)
  File "/Users/garrett/code/micahflee/onionshare/env/lib/python2.7/site-packages/py2app/build_app.py", line 824, in process_recipes
    rval = check(self, mf)
  File "/Users/garrett/code/micahflee/onionshare/env/lib/python2.7/site-packages/py2app/recipes/virtualenv.py", line 80, in check
    mf.scan_code(co, m)
AttributeError: 'ModuleGraph' object has no attribute 'scan_code'
```

A Google search shows that this is a [known](http://www.marinamele.com/from-a-python-script-to-a-portable-mac-application-with-py2app) problem in py2app. The workaround is to edit `py2app/recipes/virtualenv.py` and prepend an `_` before `scan_code` and `load_module` :cry:.

Further testing shows that this problem only occurs when building in a virtualenv. If I install the dependencies locally (`sudo pip install`) and build without a virtualenv, the build succeeds without errors.

This isn't really a problem in OnionShare, and the docs don't recommend using a virtualenv, so I can't fault them for this issue. However, using a virtualenv for development dependencies is generally a best practice so it would be good to support it without having to resort to hacky workarounds. I'm not sure if this is something OnionShare can fix, or if we should file an upstream issue on py2app to address it.

**Comment by micahflee** [comment]
OnionShare no longer uses py2app, so maybe virtualenv support is easier now.

**Comment by mig5** [comment]
I don't reproduce this working in a virtualenv these days - everything seems to go fine (one thing: rather than use ```sudo``` to ```pip -r install install/requirements.txt``` per the BUILD.md, I drop the sudo so as not to break out of the virtualenv) - so I'll close this old ticket.
