### ISSUE TITLE
Crashes in TAILS 1.8.1

### ISSUE THREAD

**Issue by hopefulguy2016** [micahflee/onionshare#257]
sudo onionshare filename
Connecting to Tor control port to set up hidden service on port 43149.
Traceback (most recent call last):
  File "/usr/bin/onionshare", line 29, in <module>
    onionshare.main()
  File "/usr/lib/python2.7/dist-packages/onionshare/onionshare.py", line 137, in main
    app.start_hidden_service()
  File "/usr/lib/python2.7/dist-packages/onionshare/onionshare.py", line 75, in start_hidden_service
    self.onion_host = self.hs.start(self.port)
  File "/usr/lib/python2.7/dist-packages/onionshare/hs.py", line 128, in start
    self.c.set_options(self._hsdic2list(hsdic))
  File "/usr/lib/python2.7/dist-packages/stem/control.py", line 1889, in set_options
    raise stem.InvalidRequest(response.code, response.message)
stem.InvalidRequest: Unacceptable option value: Failed to configure rendezvous options. See logs for details.

**Comment by micahflee** [comment]
Unfortunately Tails isn't support until #220 gets resolved.
