### ISSUE TITLE
building 0.9.1 fails due to python dependancies 

### ISSUE THREAD

**Issue by freddymartinez9** [micahflee/onionshare#290]
Hi Micah,

The current build instructions on debian jessie fail because python3-nose isn't listed as a dependency. stacktrace below: 

```
dpkg-checkbuilddeps: Unmet build dependencies: python3-nose
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
Traceback (most recent call last):
  File "setup.py", line 103, in <module>
    (os.path.join(sys.prefix, 'share/onionshare/html'), html)
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/stdeb/command/bdist_deb.py", line 48, in run
    util.process_command(syscmd,cwd=target_dirs[0])
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 169, in process_command
    check_call(args, cwd=cwd)
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 45, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 3
```

**Comment by u451f** [comment]
Hi Freddy,

if you want to you can copy the dependencies from the official Debian package: 
https://anonscm.debian.org/cgit/pkg-privacy/packages/onionshare.git/tree/debian/control?h=debian

It builds correctly but it's hit by this bug: https://github.com/micahflee/onionshare/issues/284
That's why the new version is not yet in Debian.

Cheers!
