### ISSUE TITLE
Switch from PyInstaller to cx_Freeze

### ISSUE THREAD

**Issue by RyanSinger** [micahflee/onionshare#302]
Hey,

Onionshare was crashing on launch, so I decided to see if it would behave it I built it myself. Unfortunately, the build also fails.

```
Ryans-MacBook-Pro:onionshare ryan$ ./install/build_osx.sh 
Deleting dist folder
Building OnionShare.app
238 INFO: PyInstaller: 3.2
238 INFO: Python: 3.5.2
253 INFO: Platform: Darwin-15.5.0-x86_64-i386-64bit
258 INFO: UPX is not available.
266 INFO: Extending PYTHONPATH with paths
['/Users/ryan/onionshare/install/scripts', '/Users/ryan/onionshare']
267 INFO: checking Analysis
311 INFO: Appending 'datas' from .spec
337 INFO: checking PYZ
356 INFO: checking PKG
356 INFO: Building PKG because out00-PKG.toc is non existent
358 INFO: Building PKG (CArchive) out00-PKG.pkg
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.2', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 41, in <module>
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/building/api.py", line 398, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/building/api.py", line 189, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/building/datastruct.py", line 178, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/building/api.py", line 274, in assemble
    pylib_name=pylib_name)
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/archive/writers.py", line 329, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/archive/writers.py", line 59, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/archive/writers.py", line 84, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/archive/writers.py", line 370, in add
    code = get_code_object(nm, pathnm)
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/building/utils.py", line 545, in get_code_object
    co = _load_code(modname, filename)
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/building/utils.py", line 521, in _load_code
    assert loader and hasattr(loader, 'get_code')
AssertionError
Ryans-MacBook-Pro:onionshare ryan$ 
```

**Comment by micahflee** [comment]
This is a bug in the new version of PyInstaller, which #286 aims to fix. However, after setting up a brand new Windows development environment, I've run into other issues related to PyInstaller, even with downgrading to 3.1.1.

I've been experimenting with switching from PyInstaller to cx_Freeze, and so far it's working great in Windows. If I switch to cx_Freeze in OS X as well, hopefully it will finally fix #274 too (which is also PyInstaller's fault).

I'm going to officially make this the issue to switch to cx_Freeze.
