### ISSUE TITLE
Exception when I close Onionshare GUI on Linux

### ISSUE THREAD

**Issue by mig5** [micahflee/onionshare#424]
Sometimes when I close the GUI on Linux, after starting the app from dev_scripts/onionshare-gui from terminal:

```
[May 28 2017 09:23:13 AM] OnionShareGui.closeEvent
[May 28 2017 09:23:13 AM] Onion.cleanup
Traceback (most recent call last):
  File "/home/user/onionshare/onionshare_gui/__init__.py", line 110, in shutdown
    onion.cleanup()
  File "/home/user/onionshare/onionshare/onion.py", line 428, in cleanup
    self.tor_proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
```

Maybe just needs a try/except (pass) to be less noisy?

**Comment by mig5** [comment]
Possible that this is just an issue running self.tor_proc.terminate() on a system tor?

```
        # Stop tor process
        if self.tor_proc:
            self.tor_proc.terminate()
            time.sleep(0.2)
            if not self.tor_proc.poll():
                self.tor_proc.kill()
            self.tor_proc = None
```

**Comment by mig5** [comment]
I switched to Fedora24 and I can't reproduce this any more. More Debian 8 weirdness. Sorry for the noise.
