### ISSUE TITLE
On Linux, when Tor taking too long to download, saving SettingsDialog crashes

### ISSUE THREAD

**Issue by mig5** [micahflee/onionshare#425]
If Tor takes too long to connect and throws the dialog message about it, and I click OK and am taken to the SettingsDialog, if I click Save, I get a crash

```
[May 28 2017 09:32:20 AM] SettingsDialog.save_clicked
[May 28 2017 09:32:20 AM] SettingsDialog.settings_from_fields
[May 28 2017 09:32:20 AM] Settings.__init__
[May 28 2017 09:32:20 AM] Settings.load
[May 28 2017 09:32:20 AM] Settings.save
Settings saved to /home/user/.config/onionshare/onionshare.json
[May 28 2017 09:32:20 AM] SettingsDialog.save_clicked: rebooting the Onion
[May 28 2017 09:32:20 AM] Onion.cleanup
Traceback (most recent call last):
  File "/home/user/onionshare/onionshare_gui/settings_dialog.py", line 487, in save_clicked
    self.onion.cleanup()
  File "/home/user/onionshare/onionshare/onion.py", line 428, in cleanup
    self.tor_proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
```

Looks maybe the same sort of issue as https://github.com/micahflee/onionshare/issues/424 - in this case, triggered when attempting to reboot the Tor connection (as opposed to simply closing altogether)

**Comment by mig5** [comment]
I am not sure if these sorts of issues are symptoms of using dev_scripts/onionshare-gui with bundled Tor. I never reproduce this or #424 on Mac with the app built via install/build_osx.sh.

**Comment by mig5** [comment]
It doesn't occur on Fedora24.. as per #424, probably Debian 8 weirdness... sorry.
