### ISSUE TITLE
Onionshare gets stuck when I close TorBrowser

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#493]
Onionshare gets stuck when I close TorBrowser.
1. Open onionshare and make sure TorBrowser and "start a share in onionshare"
2. Close TorBrowser when the onion link is generated.
3. Click "stop sharing" and then click "start sharing", it will cause a traceback and get stuck at "Please wait" and nothing happens.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jackimoore/Desktop/untitled folder/onionshare-master/onionshare_gui/onionshare_gui.py", line 250, in start_onion_service
    self.app.start_onion_service()
  File "/Users/"User"/Desktop/untitled folder/onionshare-master/onionshare/onionshare.py", line 79, in start_onion_service
    self.onion_host = self.onion.start_onion_service(self.port)
  File "/Users/"User"/Desktop/untitled folder/onionshare-master/onionshare/onion.py", line 404, in start_onion_service
    res = self.c.create_ephemeral_hidden_service({ 80: port }, await_publication=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/stem/control.py", line 2903, in create_ephemeral_hidden_service
    response = self.msg(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/stem/control.py", line 627, in msg
    self._socket.send(message)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/stem/socket.py", line 126, in send
    raise stem.SocketClosed()
stem.SocketClosed

```

**Comment by micahflee** [comment]
This is fixed now thanks to #503. I just tested using Tor Browser, and confirmed that if a share is active and you close Tor Browser, it stops the share and alerts the user.
