### ISSUE TITLE
Add python3-distutils dependency for Ubuntu

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#715]
I received this bug report:

> Hi I just found that your PPA-provided Onionshare wouldn't launch on newly installed Ubuntu 18.04 'Bionic'. When trying with CLI command 'onionshare-gui', terminal spits the following :

```
Traceback (most recent call last):
  File "/usr/bin/onionshare-gui", line 21, in <module>
    import onionshare_gui
  File "/usr/lib/python3/dist-packages/onionshare_gui/__init__.py", line
22, in <module>
    from .alert import Alert
  File "/usr/lib/python3/dist-packages/onionshare_gui/alert.py", line
22, in <module>
    from onionshare import common
  File "/usr/lib/python3/dist-packages/onionshare/__init__.py", line 24,
in <module>
    from .onion import *
  File "/usr/lib/python3/dist-packages/onionshare/onion.py", line 21, in
<module>
    from stem.control import Controller
  File "/usr/lib/python3/dist-packages/stem/control.py", line 265, in
<module>
    import stem.descriptor.microdescriptor
  File "/usr/lib/python3/dist-packages/stem/descriptor/__init__.py",
line 55, in <module>
    import stem.util.system
  File "/usr/lib/python3/dist-packages/stem/util/system.py", line 70, in
<module>
    import distutils.spawn
ModuleNotFoundError: No module named 'distutils.spawn'
```

> I installed the python3-distutils package and it works now. Like a charm. I wouln't be able to investigate whether this is the best mitigation, but it works  Should this package be added as a dependency ?

I think the answer is yes, this package should be added as a dependency :).

**Comment by mig5** [comment]
Interesting, that package doesn't exist on Debian Jessie or earlier Ubuntu... it must be new.

How to handle unique cases like this for specific distros? Maybe you can do it in your PPA packaging specifically, and we add a note in BUILD.md that it may (or may not) be a dependency?

Or, it could be pip installed perhaps regardless of distro version.

**Comment by mig5** [comment]
I think you'll need this for 2.0 since you'll be shipping it for bionic in your PPA? So I'll add it to the milestone.
