### ISSUE TITLE
Tor-related crash

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#760]
In the develop branch, when I use bundled Tor to start receive mode (using Tor 0.3.2.10 from Fedora 28 repos), it crashes:

```
$ ./dev_scripts/onionshare --receive
OnionShare 1.3.1 | https://onionshare.org/
Connecting to the Tor network: 100% - Done
Configuring onion service on port 17641.
Starting ephemeral Tor onion service and awaiting publication
Traceback (most recent call last):
  File "/home/user/code/onionshare/onionshare/onion.py", line 483, in start_onion_service
    res = self.c.create_ephemeral_hidden_service({ 80: port }, await_publication=True, key_type=key_type, key_content=key_content)
  File "/usr/lib/python3.6/site-packages/stem/control.py", line 2937, in create_ephemeral_hidden_service
    stem.response.convert('ADD_ONION', response)
  File "/usr/lib/python3.6/site-packages/stem/response/__init__.py", line 124, in convert
    message._parse_message(**kwargs)
  File "/usr/lib/python3.6/site-packages/stem/response/add_onion.py", line 31, in _parse_message
    raise stem.ProtocolError("ADD_ONION response didn't have an OK status: %s" % self)
stem.ProtocolError: ADD_ONION response didn't have an OK status: Invalid key type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./dev_scripts/onionshare", line 28, in <module>
    onionshare.main()
  File "/home/user/code/onionshare/onionshare/__init__.py", line 110, in main
    app.start_onion_service()
  File "/home/user/code/onionshare/onionshare/onionshare.py", line 86, in start_onion_service
    self.onion_host = self.onion.start_onion_service(self.port)
  File "/home/user/code/onionshare/onionshare/onion.py", line 486, in start_onion_service
    raise TorErrorProtocolError(strings._('error_tor_protocol_error'))
onionshare.onion.TorErrorProtocolError: Could not communicate with the Tor controller.
If you're using Whonix, check out https://www.whonix.org/wiki/onionshare to make OnionShare work.
```

I think this has something to do with my system tor version being too old.

**Comment by mig5** [comment]
:/

Is there any difference when you enable Legacy Mode? (I assume this tried a v3 onion)

**Comment by mig5** [comment]
'Invalid key type" means it couldn't understand the v3 key somehow..

**Comment by micahflee** [comment]
Good call, I will try enabling legacy mode. The first thing I'm doing though is catching these exceptions properly.

Note that I don't get this error when I'm using a new version of Tor, from Tor Browser.

**Comment by mig5** [comment]
So we need to tweak the version check, line 463 or so of onionshare/onion.py, do you want to roll that into that same PR?

**Comment by micahflee** [comment]
Awesome thanks for finding that! Yup I'll do that

**Comment by micahflee** [comment]
Ok, PR ready for review
