### ISSUE TITLE
Stop aborting on failing to find a free port the first time

### ISSUE THREAD

**Issue by mig5** [micahflee/onionshare#792]
We are hitting this a bit more often than we used to:

```
Traceback (most recent call last):
  File "/home/user/git/onionshare/onionshare/common.py", line 433, in get_available_port
    tmpsock.bind(("127.0.0.1", random.randint(min_port, max_port)))
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/git/onionshare/onionshare/onionshare.py", line 67, in choose_port
    self.port = self.common.get_available_port(17600, 17650)
  File "/home/user/git/onionshare/onionshare/common.py", line 436, in get_available_port
    raise OSError(e)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/git/onionshare/onionshare_gui/threads.py", line 76, in run
    self.mode.app.choose_port()
  File "/home/user/git/onionshare/onionshare/onionshare.py", line 69, in choose_port
    raise OSError(strings._('no_available_port'))
OSError: Could not find an available port to start the onion service
```

This dates back to this PR: https://github.com/micahflee/onionshare/pull/484

if you look at the diff there - we used to 'pass' a port clash in a `while True` loop.

This could lead to a hang if all ports are in use. So I tried to make it abort more cleanly with the error message.

Unfortunately I didn't think about the implication: the very first time it tries a random port that's in use, it will just abort. It should go back to the old behaviour of trying for another port. Maybe that PR should just be reverted, but note the mention about the 'port 0' bug that I think the PR 'fixed'... we don't want to reintroduce that bug either.

**Comment by mig5** [comment]
Looks like this was fixed in https://github.com/micahflee/onionshare/commit/75153db11e81972621c920788c3ad432e7b4a152
