### ISSUE TITLE
Fails to build on Debian 9 due to upstream error in dh-python

### ISSUE THREAD

**Issue by heartsucker** [micahflee/onionshare#803]
Sys info

```
$ uname -a
Linux pythagoras 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch
```

```
dpkg-buildpackage: info: source changed by Micah Lee <micah@micahflee.com>
 dpkg-source --before-build onionshare-2.0~dev
 fakeroot debian/rules clean
dh clean --with python3 --buildsystem=pybuild
   dh_testdir -O--buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
E: Please add apropriate interpreter package to Build-Depends, see pybuild(1) for details at /usr/share/perl5/Debian/Debhelper/Buildsystem/pybuild.pm line 199.
debian/rules:7: recipe for target 'clean' failed
make: *** [clean] Error 25
```

This appears to be a bug with `dh-python`: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828883

It says it was closed, but this seems to be the exact same issue. (and reporting it here for others)

```
$ apt-cache policy dh-python
dh-python:
  Installed: 2.20170125
  Candidate: 2.20170125
  Version table:
 *** 2.20170125 500
        500 http://ftp.us.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by mig5** [comment]
Hi @heartsucker,

I encountered this on Debian Stretch too. The thing is though, OnionShare 2.0 (basically what you are seeing in the `develop` branch right now) won't run on Debian Stretch anyway as we are introducing support for v3 onions which depends on other Python packages that aren't yet in Stretch/python version too old in Stretch.

You can get around this problem by upgrading to Buster and then a .deb will build cleanly.

We have a ticket about getting the relevant python packages backported to Stretch in order to support building on Stretch.

See this comment: https://github.com/micahflee/onionshare/pull/772#issuecomment-423655423

Sorry for the inconvenience. If you need to build a .deb of the last stable release (1.3.1) on Stretch, you can build off of `master` branch.

**Comment by micahflee** [comment]
I'm actually hitting the same bug in buster too now:

```
dpkg-buildpackage: info: source changed by Micah Lee <micah@micahflee.com>
 dpkg-source --before-build .
 fakeroot debian/rules clean
dh clean --with python3 --buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
E: Please add apropriate interpreter package to Build-Depends, see pybuild(1) for details at /usr/share/perl5/Debian/Debhelper/Buildsystem/pybuild.pm line 224.
make: *** [debian/rules:7: clean] Error 25
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
Traceback (most recent call last):
  File "setup.py", line 95, in <module>
    data_files=data_files
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/stdeb/command/bdist_deb.py", line 22, in run
    self.run_command('sdist_dsc')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/stdeb/command/sdist_dsc.py", line 140, in run
    remove_expanded_source_dir=self.remove_expanded_source_dir,
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 1397, in build_dsc
    dpkg_genchanges(cwd=fullpath_repackaged_dirname)
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 538, in dpkg_genchanges
    process_command(args,cwd=cwd)
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 183, in process_command
    check_call(args, cwd=cwd)
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 46, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 2
OnionShare failed to build!
```
